//For uncompressed source code, visit https://github.com/tonY1883/jsonedit
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");var data,currentNode,currentNodeMaxIndex,currentNodePath,autoTypeConvert=!0,fname,copiedNode;
function loadFile(a){var b=$('<input type="file">');a&&b.attr("accept",a);b.change(function(){var a=b[0].files[0];fname=a.name;var d=new FileReader;d.onload=function(a){loadData(a.target.result)};d.readAsText(a)});b.click()}
function loadData(a){try{data=JSON.parse(a)}catch(b){alert("Your JSON contains syntax errors!\nFail to parse JSON: "+b.message);return}$("#save-json-button").css("visibility","visible");$("#browser").css("visibility","visible");void 0!==fname?$("title").text("JSONEdit: "+fname):fname="JSON.json";a={core:{}};a.core.data=assembleTreeJson(data);a.plugins=["search"];a.search={case_insensitive:!0,show_only_matches:!0};$("#tree").jstree("destroy").jstree(a);$("#editor-content").empty()}
function assembleTreeJson(a,b){var c={};void 0===b&&(b=a.constructor.name);c.text=b;c.icon=!1;if(Array.isArray(a)){c.icon="img/array-s.png";var d=[],e=!1;$.each(a,function(a,b){var c=a.toString();if(isObject(b)||Array.isArray(b))e=!0,d[a]=assembleTreeJson(b,c)});e&&(c.children=d);return c}if(isObject(a)){c.icon="img/object-s.png";d=[];var f=0;$.each(a,function(a,b){if(isObject(b)||Array.isArray(b))d[f]=assembleTreeJson(b,a),f++});c.children=d;return c}return null}
function loadDatum(a){var b=a.split(">"),c=$("#editor-content");c.empty().unbind();var d=data;for(var e=1;e<b.length;e++)d=d[b[e]];currentNode=d;currentNodePath=a;Array.isArray(currentNode)?(currentNodeMaxIndex=currentNode.length,$.each(currentNode,function(a,b){isObject(b)?c.append('<div class="table-row"><input class="key-input" readonly value='+a+'> : <textarea class="table-cell value-input" readonly value='+JSON.stringify(b)+' id="id-input">'+JSON.stringify(b)+'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):
c.append('<div class="table-row"><input class="key-input" readonly value='+a+'> : <textarea class="table-cell value-input" value='+b+' id="id-input">'+b+'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')})):$.each(d,function(a,b){isObject(b)?c.append('<div class="table-row"><input class="key-input" value='+a+'> : <textarea class="table-cell value-input" readonly value='+JSON.stringify(b)+' id="id-input">'+JSON.stringify(b)+
'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):c.append('<div class="table-row"><input class="key-input" value='+a+'> : <textarea class="table-cell value-input" value='+b+' id="id-input">'+b+'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')});$(".new").length||(c.append('<div class="table-row" id=\'new-row\'><button class="new" ><i class="material-icons" style="vertical-align: middle;">add_circle</i>New...</button> <ul class=\'menu\' id=\'new-option\'><li class="menu-items" id="new-value-button"><a >Value</a></li><li class="menu-items"id="new-array-button"><a >Array</a></li><li class="menu-items"id="new-object-button"><a >Object</a></li></ul></div>'),
$(".new").click(function(){$("#new-option").show()}),$("#new-value-button").click(function(){$("#new-option").hide();(Array.isArray(currentNode)?$('<div class="table-row"><input class="key-input" readonly value=""> : <textarea class="table-cell value-input"  id="id-input"> </textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):$('<div class="table-row"><input class="key-input" > : <textarea class="table-cell value-input"  id="id-input"> </textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')).insertBefore($("#new-row"));
reloadIndices()}),$("#new-array-button").click(function(){$("#new-option").hide();(Array.isArray(currentNode)?$('<div class="table-row"><input class="key-input" readonly value=""> : <textarea class="table-cell value-input"  readonly id="id-input">[]</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):$('<div class="table-row"><input class="key-input" > : <textarea class="table-cell value-input" readonly id="id-input">[]</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')).insertBefore($("#new-row"));
reloadIndices()}),$("#new-object-button").click(function(){$("#new-option").hide();(Array.isArray(currentNode)?$('<div class="table-row"><input class="key-input" readonly value=""> : <textarea class="table-cell value-input"  readonly id="id-input">{}</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):$('<div class="table-row"><input class="key-input" > : <textarea class="table-cell value-input" readonly id="id-input">{}</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')).insertBefore($("#new-row"));
reloadIndices()}));$("#save-btn").length||($("#editor-content").append($('<button id="save-btn" class="save-btn raised-button">Save</button>')),$("#save-btn").click(function(){saveDatum()}));c.on("keydown",".key-input[readonly]",function(){alert("Array indices cannot be modified!")});c.on("keydown",".value-input[readonly]",function(){alert("Objects and arrays must be edited in their own node!")});c.on("click",".delete-row",function(){$(this).parent().remove();Array.isArray(currentNode)&&reloadIndices()});
$("#edit-button").css("visibility","visible")}function reloadIndices(){if(Array.isArray(currentNode)){var a=$(".key-input");$.each(a,function(a,c){c.value=a})}}function copyDatum(){copiedNode=JSON.stringify(currentNode);alert("Current element copied.")}
function pasteDatum(){copiedNode&&((Array.isArray(currentNode)?$('<div class="table-row"><input class="key-input" readonly value=""> : <textarea class="table-cell value-input"  readonly id="id-input">'+copiedNode+'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>'):$('<div class="table-row"><input class="key-input" > : <textarea class="table-cell value-input" readonly id="id-input">'+copiedNode+'</textarea><button class=\'delete-row\'><i class="material-icons" style="vertical-align: middle;">remove_circle</i>Delete</button></div>')).insertBefore($("#new-row")),
reloadIndices())}
function saveDatum(){var a=JSON.parse(JSON.stringify(currentNode)),b=Object.keys(a);a=$(".key-input");var c=[],d=$(".value-input");$.each(a,function(a,f){c.push(f.value);$(d[a]).prop("readonly")?-1<$.inArray(f.value,b)||(currentNode[f.value]=JSON.parse(d[a].value)):autoTypeConvert?isNumber(d[a].value)?currentNode[f.value]=Number(d[a].value):currentNode[f.value]="true"===d[a].value?!0:"false"===d[a].value?!1:d[a].value:currentNode[f.value]=d[a].value});$.each(b,function(a,b){0>$.inArray(b,c)&&delete currentNode[b]});
loadData(JSON.stringify(data));alert("Content saved.")}function isObject(a){return a===Object(a)}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}function saveFile(){var a=JSON.stringify(data),b=document.createElement("a");b.setAttribute("download",fname);b.href=window.URL.createObjectURL(new Blob([a],{type:"application/json"}));document.body.appendChild(b);window.requestAnimationFrame(function(){b.click();document.body.removeChild(b)})}$("#save-file-button").click(function(){saveFile()});
$("#load-file-button").click(function(){loadFile(".json")});
$("#new-json-button").click(function(){if(void 0===data||confirm("Creating a new JSON will discard the JSON you are currently editing.\nAre you sure you want to continue?"))$("#modal-new-json-bg").show(),window.onclick=function(a){a.target==$("#modal-new-json-bg")[0]&&$("#modal-new-json-bg").hide()},$("#new-json").click(function(){!0===$("#option-ary")[0].checked?(loadData("[]"),$("#modal-new-json-bg").hide()):!0===$("#option-obj")[0].checked&&(loadData("{}"),$("#modal-new-json-bg").hide())})});
$("#setting-button").click(function(){$("#modal-setting-bg").show();window.onclick=function(a){a.target==$("#modal-setting-bg")[0]&&$("#modal-setting-bg").hide()};$("#save-setting").click(function(){autoTypeConvert=$("#option-type-convert")[0].checked;$("#modal-setting-bg").hide()})});
$("#save-string-button").click(function(){$("#modal-string-out-bg").show().click(function(a){$(this).hide()}).children().click(function(a){return!1});$("#string-output").val(JSON.stringify(data)).focus().select();$("#copy-string").click(function(){$("#string-output").focus().select();document.execCommand("copy");alert("Output JSON copied to your clipboard.")})});
$("#load-string-button").click(function(){$("#modal-string-bg").show().click(function(a){$(this).hide()}).children().click(function(a){return!1});$("#load-string").click(function(){loadData($("#string-input").val());$("#modal-string-bg").hide()})});$("#copy-button").click(function(){copyDatum()});$("#paste-button").click(function(){pasteDatum()});$("#searchbox").keyup(function(){var a=$(this).val();$("#tree").jstree("search",a)});
$(document).on("click",".jstree-anchor",function(a){a=$(this).parent().attr("id");a.substring(a.indexOf("_")+1,a.length);loadDatum($("#tree").jstree().get_path($("#tree").jstree("get_selected",!0)[0],">"))});
